### PR TITLE
Add haml 6 support

### PR DESCRIPTION
**Pull request by fauresebast**
This PR add a fix and tests for Haml versions >= 6.0

### CODE REVIEW

**Comment by daveallie** [comment]
@fauresebast would you mind rebasing this, just so the diff is a bit easier to read and the tests run.

**Comment by fauresebast** [comment]
@daveallie done! 😁

**Comment by daveallie** [comment]
Thanks @fauresebast!

**Comment by daveallie** [comment]
Published these changes, they're available in version 0.4.0

**Pull request merged**
